import json
import os

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DATA_FILE = os.path.join(BASE_DIR, 'data', 'aqi_sample.json')

class AQIService:
    def __init__(self):
        self.data = self._load_data()

    def _load_data(self):
        if os.path.exists(DATA_FILE):
            with open(DATA_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        return {}

    def get_aqi_category(self, aqi):
        if aqi <= 50:
            return "Good", "text-success", "badge-good", "#10B981"
        elif aqi <= 100:
            return "Satisfactory", "text-info", "badge-satisfactory", "#06B6D4"
        elif aqi <= 200:
            return "Moderate", "text-warning", "badge-moderate", "#F59E0B"
        elif aqi <= 300:
            return "Poor", "text-orange", "badge-poor", "#F97316"
        elif aqi <= 400:
            return "Very Poor", "text-danger", "badge-very-poor", "#EF4444"
        else:
            return "Severe / Hazardous", "text-purple", "badge-severe", "#7C3AED"

    def get_aqi_by_location(self, location_name='Pune'):
        city_data = self.data.get(location_name, self.data.get('Pune', {}))
        if not city_data:
            return None

        aqi_val = city_data.get('aqi', 100)
        cat_name, text_class, badge_class, color_hex = self.get_aqi_category(aqi_val)

        return {
            'location': location_name,
            'aqi': aqi_val,
            'category': cat_name,
            'text_class': text_class,
            'badge_class': badge_class,
            'color_hex': color_hex,
            'pm25': city_data.get('pm25', 40.0),
            'pm10': city_data.get('pm10', 70.0),
            'no2': city_data.get('no2', 25.0),
            'so2': city_data.get('so2', 15.0),
            'co': city_data.get('co', 1.0),
            'o3': city_data.get('o3', 25.0),
            'dominant_pollutant': city_data.get('dominant_pollutant', 'PM2.5'),
            'history': city_data.get('history', []),
            'hotspots': city_data.get('hotspots', [])
        }

    def analyze_causes(self, location_name='Pune', simulated_aqi=None):
        base_data = self.get_aqi_by_location(location_name)
        aqi = simulated_aqi if simulated_aqi is not None else (base_data['aqi'] if base_data else 100)
        dominant = base_data.get('dominant_pollutant', 'PM2.5') if base_data else 'PM2.5'

        causes = []
        source_breakdown = {}

        if dominant == 'PM2.5' or aqi > 150:
            causes.append({
                'source': 'Vehicular Transport & Congestion',
                'contribution_pct': 38,
                'description': 'High volume of diesel freight, heavy peak-hour idling, and two-stroke commuter traffic along key transit corridors.',
                'icon': 'bi-truck-front'
            })
            causes.append({
                'source': 'Construction & Road Resuspension Dust',
                'contribution_pct': 26,
                'description': 'Unmitigated construction earthworks, unpaved shoulders, and aggregate transport generating fine airborne particulate.',
                'icon': 'bi-cone-striped'
            })
            causes.append({
                'source': 'Industrial & Micro-Manufacturing Emissions',
                'contribution_pct': 22,
                'description': 'Fuel oil and petcoke boilers operating across industrial clusters without adequate flue gas scrubbers.',
                'icon': 'bi-buildings'
            })
            causes.append({
                'source': 'Open Biomass & Municipal Waste Burning',
                'contribution_pct': 14,
                'description': 'Localized garbage incineration and agricultural residue fires on urban peripheries.',
                'icon': 'bi-fire'
            })
            source_breakdown = {
                'Vehicular': 38,
                'Construction': 26,
                'Industrial': 22,
                'Biomass Burning': 14
            }
        elif dominant == 'PM10':
            causes.append({
                'source': 'Construction & Demolition Activities',
                'contribution_pct': 45,
                'description': 'Excavation, demolition dust, dry cement handling, and non-sprinkled haulage.',
                'icon': 'bi-hammer'
            })
            causes.append({
                'source': 'Road & Soil Dust Resuspension',
                'contribution_pct': 30,
                'description': 'Dry road surface turbulence generated by high-speed vehicular traffic.',
                'icon': 'bi-wind'
            })
            causes.append({
                'source': 'Industrial Dust Emissions',
                'contribution_pct': 25,
                'description': 'Crushing units, stone quarries, and metallurgical processing units.',
                'icon': 'bi-gear-wide-connected'
            })
            source_breakdown = {
                'Construction': 45,
                'Road Dust': 30,
                'Industrial Dust': 25
            }
        else:
            causes.append({
                'source': 'Thermal & Chemical Industrial Combustion',
                'contribution_pct': 50,
                'description': 'Gaseous emissions containing sulphur and nitrogen oxides.',
                'icon': 'bi-funnel-fill'
            })
            causes.append({
                'source': 'Heavy Diesel Combustion',
                'contribution_pct': 35,
                'description': 'High-capacity diesel generator sets and commercial transport.',
                'icon': 'bi-fuel-pump'
            })
            causes.append({
                'source': 'Secondary Smog Photochemical Formation',
                'contribution_pct': 15,
                'description': 'Atmospheric reaction of volatile compounds under intense solar radiation.',
                'icon': 'bi-sun'
            })
            source_breakdown = {
                'Industrial Combustion': 50,
                'Diesel Fleet': 35,
                'Secondary Photochemical': 15
            }

        return {
            'aqi': aqi,
            'dominant_pollutant': dominant,
            'causes': causes,
            'source_breakdown': source_breakdown
        }
